spring.application.name=EmployeeManagmentSystem
server.port = 2027

#Spring Database Properties
#Postgresql Driver
spring.datasource.driver-class-name= org.postgresql.Driver
##Data connection url
spring.datasource.url= jdbc:postgresql://localhost:5432/employeemanagement
#Username and Password
spring.datasource.username= postgres
spring.datasource.password= aquilanamos

#Hibernate settings
spring.jpa.hibernate.ddl-auto= update
#Show sql queries in the console for debugging
spring.jpa.show-sql= true


#Email Configurations
#SMPT for sending emails via Gmail
spring.mail.host= smtp.gmail.com
#SMPT port (587 for Tls, 465 for SSL)
spring.mail.port= 587

spring.mail.username=uwilaminango2604@gmail.com
spring.mail.password= vyjf iqdh jyjm vgzn

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



